### ISSUE TITLE
Graphs not populating

### ISSUE THREAD

**Issue by TylerADavis** [paramshah10/VA-dashboard#2]
I noticed on the morning of January 6 that the dashboard is not loading properly. I expected for all of the graphs and data fields to populate with the data in [charts_data.js](https://github.com/paramshah10/VA-dashboard/blob/5cf4e91b71634d6eb8948304ca22267dae66bfeb/src/variables/charts_data.js), but when I view the model website the graphs never populate and a loading icon spins. I'm not sure when this issue actually began, so I'm not sure whether or not this is related to #1 . Please let me know if there is any more information I can provide, or if you have any difficulty reproducing this.

# Steps to reproduce
1. Visit https://paramshah10.github.io/VA-dashboard/#/admin/index and view the model website
2. Observe that the graphs do not load

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/16804460/104155376-ee6ba380-539b-11eb-9e3d-6204b222de82.png">

**Comment by TylerADavis** [comment]
This may be due to an issue with firebase / the GCP config. I'm seeing errors related to permissions and firebase in the console (see image below).

<img width="854" alt="image" src="https://user-images.githubusercontent.com/16804460/104219995-b42df080-53f3-11eb-8318-ab6540f4e0d9.png">

**Comment by TylerADavis** [comment]
I substituted in the GCP configuration from the warrior wellness dashboard and that allowed the page to load, so I believe it's definitely an issue with the GCP config.

**Comment by paramshah10** [comment]
Hey Tyler, sorry for the late reply

The issue was caused because we did not change the default database rules that only allow us to perform database operations until 30 days from the creation of the database. The date passed and hence firebase blocked all requests to read/write/delete from firestore.

I fixed it by just changing the rules. You can see them under Firestore -> Rules.

The new rules are:
  match /users/{userId}/{document=**} {
        allow read, write, update, delete: if request.auth != null && request.auth.uid == userId;
        allow create: if request.auth != null;
      }

This rule roughly translate to "only let the users access their own data." I created the database such that each user has its own document of data inside the 'users' collection and the name of the document matches the user's unique ID generated by firebase. So this rule checks the UID of the person performing the read/write request and matches it to the document ID. If they match, meaning the user is trying to access their own data, the rule "succeeds" and the operation is completed. If not, we block the operation.

**Comment by paramshah10** [comment]
You can now switch back to the VA config

**Comment by TylerADavis** [comment]
Looks like it's loading perfectly now, thanks!
